[package]
name = "async_cache"
version = "0.1.0"
authors = ["Isaac Whitfield <iw@whitfin.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
async-timer = "0.7"
tokio = { version = "1", features = ["sync"] }

[dev-dependencies]
async-std = "1.9"
smol = "1.2"
tokio = { version = "1", features = ["full"] }
